version: "2"
services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
     - "80:80"
    volumes:
     - ./:/var/www/html
    depends_on:
     - mongo
     - redis
    links:
     - mongo
     - redis
  mongo:
     image: 'bitnami/mongodb:latest'
     container_name: mongo
     environment:
           - MONGODB_USERNAME=user
           - MONGODB_PASSWORD=user123
           - MONGODB_DATABASE=test_db
     ports:
       - "27017:27017"
     volumes:
       - ./docker:/bitnami
  redis:
     container_name: redis
     image: "redis:alpine"
